name: exampleの出力結果画像が最新かどうかのテスト

# 参考元: https://sue445.hatenablog.com/entry/2021/01/07/004835#Q-%E3%81%A0%E3%81%A3%E3%81%9F%E3%82%89pull_request%E3%81%AF%E4%B8%8D%E8%A6%81%E3%81%A7%E3%81%AF
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -euxo pipefail {0}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v4

      - name: sassコマンドのインストール
        run: npm install -g sass

      - name: コミットに含まれるスライド画像をバックアップ
        run: mkdir example-backup && mv example/example.0* example-backup

      - name: 一度すべて削除して再ビルド
        run: make clean all

      - name: 再ビルドの結果がコミットした結果と一致しているかチェック
        run: |
          result="$(composite -compose difference \
            example/example.001.png \
            example-backup/example.001.png \
            - | \
            identify -format "%[mean]" -)"
          (( $(echo "0.001 > $result" |bc -l) ))

          result="$(composite -compose difference \
            example/example.002.png \
            example-backup/example.002.png \
            - | \
            identify -format "%[mean]" -)"
          (( $(echo "0.001 > $result" |bc -l) ))

          result="$(composite -compose difference \
            example/example.003.png \
            example-backup/example.003.png \
            - | \
            identify -format "%[mean]" -)"
          (( $(echo "0.001 > $result" |bc -l) ))

          result="$(composite -compose difference \
            example/example.004.png \
            example-backup/example.004.png \
            - | \
            identify -format "%[mean]" -)"
          (( $(echo "0.001 > $result" |bc -l) ))

          result="$(composite -compose difference \
            example/example.005.png \
            example-backup/example.005.png \
            - | \
            identify -format "%[mean]" -)"
          (( $(echo "0.001 > $result" |bc -l) ))

      - name: 検証しやすいようにビルド結果をartifactへ保存
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: example
          path: example
          if-no-files-found: error

      - name: 結果画像をコミットへ貼り付け
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const script = require('./.github/github-script.js')
            console.log(await script({ github, context }))
